#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROTO_ROOT="${ROOT_DIR}/neofs-api"
OUT_DIR="${ROOT_DIR}/src/proto/gen"
PLUGIN_BIN="${ROOT_DIR}/.zig-cache/protoc-gen-zig-arwalk"
PROTOBUF_SRC_DIR="${PROTOBUF_SRC_DIR:-}"

if [[ ! -d "${PROTO_ROOT}" ]]; then
  echo "neofs-api submodule is missing at ${PROTO_ROOT}" >&2
  exit 1
fi

if [[ -z "${PROTOBUF_SRC_DIR}" ]]; then
  for cache_dir in "${ROOT_DIR}/.zig-cache/p" "${HOME}/.cache/zig/p"; do
    if [[ -d "${cache_dir}" ]]; then
      PROTOBUF_SRC_DIR="$(ls -dt "${cache_dir}"/protobuf-* 2>/dev/null | head -n1 || true)"
      if [[ -n "${PROTOBUF_SRC_DIR}" && -d "${PROTOBUF_SRC_DIR}" ]]; then
        break
      fi
    fi
  done
fi
if [[ -z "${PROTOBUF_SRC_DIR}" || ! -d "${PROTOBUF_SRC_DIR}" ]]; then
  echo "zig-protobuf sources not found. Run 'zig build --fetch' in ${ROOT_DIR} first." >&2
  exit 1
fi

rm -rf "${OUT_DIR}"
mkdir -p "${OUT_DIR}"
mkdir -p "$(dirname "${PLUGIN_BIN}")"

zig build-exe \
  --name protoc-gen-zig-arwalk \
  --dep protobuf \
  -Mroot="${PROTOBUF_SRC_DIR}/bootstrapped-generator/main.zig" \
  -Mprotobuf="${PROTOBUF_SRC_DIR}/src/protobuf.zig" \
  -femit-bin="${PLUGIN_BIN}" >/dev/null

mapfile -d '' PROTO_FILES < <(find "${PROTO_ROOT}" -name '*.proto' -print0 | sort -z)
if [[ "${#PROTO_FILES[@]}" -eq 0 ]]; then
  echo "no .proto files found in ${PROTO_ROOT}" >&2
  exit 1
fi

protoc \
  --plugin=protoc-gen-zig="${PLUGIN_BIN}" \
  --proto_path="${PROTO_ROOT}" \
  --zig_out="${OUT_DIR}" \
  "${PROTO_FILES[@]}" >/dev/null

python - <<'PY'
import pathlib
import re

root = pathlib.Path("neofs-api")
out_root = pathlib.Path("src/proto/gen")

generated_pkg_dir = out_root / "neo" / "fs" / "v2"
if not generated_pkg_dir.exists():
    raise SystemExit(f"expected generated proto directory not found: {generated_pkg_dir}")

def rewrite_pb_imports(content: str) -> str:
    return re.sub(
        r'@import\("([a-z0-9_]+)\.pb\.zig"\)',
        lambda m: f'@import("../{m.group(1)}/types.pb.zig")',
        content,
    )

modules = []
for pb_file in sorted(generated_pkg_dir.glob("*.pb.zig")):
    module = pb_file.stem[:-3] if pb_file.stem.endswith(".pb") else pb_file.stem
    modules.append(module)
    target_dir = out_root / module
    target_dir.mkdir(parents=True, exist_ok=True)
    target_file = target_dir / "types.pb.zig"
    target_file.write_text(rewrite_pb_imports(pb_file.read_text()))

def ztype(token: str) -> str:
    return f"pb.{token.split('.')[-1]}"

for service_proto in sorted(root.rglob("service.proto")):
    text = service_proto.read_text()
    m_pkg = re.search(r'^\s*package\s+([a-zA-Z0-9_.]+)\s*;', text, re.M)
    m_service = re.search(r'^\s*service\s+([A-Za-z0-9_]+)\s*\{', text, re.M)
    if not m_pkg or not m_service:
        continue
    module_base = m_pkg.group(1).split(".")[-1]
    service_name = m_service.group(1)
    out_dir = out_root / module_base
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / "service.zig"

    lines = []
    lines.append("// Code generated by scripts/genapi.sh (service VTable wrapper).")
    lines.append("// DO NOT EDIT.")
    lines.append('const pb = @import("types.pb.zig");')
    lines.append('const support = @import("../../service_support.zig");')
    lines.append("")
    lines.append(f"pub fn {service_name}(comptime UserDataType: type, comptime ErrorSet: type) type {{")
    lines.append("    return struct {")
    lines.append(f'        pub const service_name = "{service_name}";')

    for rpc in re.finditer(
        r'^\s*rpc\s+([A-Za-z0-9_]+)\s*\(\s*(stream\s+)?([A-Za-z0-9_\.]+)\s*\)\s*returns\s*\(\s*(stream\s+)?([A-Za-z0-9_\.]+)\s*\)',
        text,
        re.M,
    ):
        name = rpc.group(1)
        req_stream = rpc.group(2) is not None
        req = ztype(rpc.group(3))
        resp_stream = rpc.group(4) is not None
        resp = ztype(rpc.group(5))
        if not req_stream and not resp_stream:
            sig = f"*const fn(userdata: *UserDataType, request: {req}) ErrorSet!{resp}"
        elif not req_stream and resp_stream:
            sig = f"*const fn(userdata: *UserDataType, request: {req}, writer_queue: *support.Queue({resp})) ErrorSet!void"
        elif req_stream and not resp_stream:
            sig = f"*const fn(userdata: *UserDataType, reader_queue: *support.Queue({req})) ErrorSet!{resp}"
        else:
            sig = f"*const fn(userdata: *UserDataType, reader_queue: *support.Queue({req}), writer_queue: *support.Queue({resp})) ErrorSet!void"
        lines.append(f"        {name}: {sig},")

    lines.append("    };")
    lines.append("}")
    lines.append("")

    lines.append(f"pub fn {service_name}Server(comptime UserDataType: type, comptime ErrorSet: type) type {{")
    lines.append(f"    const VTable = {service_name}(UserDataType, ErrorSet);")
    lines.append("    return struct {")
    lines.append("        userdata: *UserDataType,")
    lines.append("        vtable: VTable,")
    lines.append("")
    lines.append("        pub fn init(userdata: *UserDataType, vtable: VTable) @This() {")
    lines.append("            return .{ .userdata = userdata, .vtable = vtable };")
    lines.append("        }")
    lines.append("")
    for rpc in re.finditer(
        r'^\s*rpc\s+([A-Za-z0-9_]+)\s*\(\s*(stream\s+)?([A-Za-z0-9_\.]+)\s*\)\s*returns\s*\(\s*(stream\s+)?([A-Za-z0-9_\.]+)\s*\)',
        text,
        re.M,
    ):
        name = rpc.group(1)
        req_stream = rpc.group(2) is not None
        req = ztype(rpc.group(3))
        resp_stream = rpc.group(4) is not None
        resp = ztype(rpc.group(5))
        if not req_stream and not resp_stream:
            sig = f"pub fn {name}(self: *@This(), request: {req}) ErrorSet!{resp}"
            call = f"return self.vtable.{name}(self.userdata, request);"
        elif not req_stream and resp_stream:
            sig = f"pub fn {name}(self: *@This(), request: {req}, writer_queue: *support.Queue({resp})) ErrorSet!void"
            call = f"return self.vtable.{name}(self.userdata, request, writer_queue);"
        elif req_stream and not resp_stream:
            sig = f"pub fn {name}(self: *@This(), reader_queue: *support.Queue({req})) ErrorSet!{resp}"
            call = f"return self.vtable.{name}(self.userdata, reader_queue);"
        else:
            sig = f"pub fn {name}(self: *@This(), reader_queue: *support.Queue({req}), writer_queue: *support.Queue({resp})) ErrorSet!void"
            call = f"return self.vtable.{name}(self.userdata, reader_queue, writer_queue);"
        lines.append(f"        {sig} {{")
        lines.append(f"            {call}")
        lines.append("        }")
        lines.append("")
    lines.append("    };")
    lines.append("}")
    lines.append("")

    lines.append(f"pub fn {service_name}Client(comptime UserDataType: type, comptime ErrorSet: type) type {{")
    lines.append(f"    const Server = {service_name}Server(UserDataType, ErrorSet);")
    lines.append("    return struct {")
    lines.append("        server: *Server,")
    lines.append("")
    lines.append("        pub fn init(server: *Server) @This() {")
    lines.append("            return .{ .server = server };")
    lines.append("        }")
    lines.append("")
    for rpc in re.finditer(
        r'^\s*rpc\s+([A-Za-z0-9_]+)\s*\(\s*(stream\s+)?([A-Za-z0-9_\.]+)\s*\)\s*returns\s*\(\s*(stream\s+)?([A-Za-z0-9_\.]+)\s*\)',
        text,
        re.M,
    ):
        name = rpc.group(1)
        req_stream = rpc.group(2) is not None
        req = ztype(rpc.group(3))
        resp_stream = rpc.group(4) is not None
        resp = ztype(rpc.group(5))
        if not req_stream and not resp_stream:
            sig = f"pub fn {name}(self: *@This(), request: {req}) ErrorSet!{resp}"
            call = f"return self.server.{name}(request);"
        elif not req_stream and resp_stream:
            sig = f"pub fn {name}(self: *@This(), request: {req}, writer_queue: *support.Queue({resp})) ErrorSet!void"
            call = f"return self.server.{name}(request, writer_queue);"
        elif req_stream and not resp_stream:
            sig = f"pub fn {name}(self: *@This(), reader_queue: *support.Queue({req})) ErrorSet!{resp}"
            call = f"return self.server.{name}(reader_queue);"
        else:
            sig = f"pub fn {name}(self: *@This(), reader_queue: *support.Queue({req}), writer_queue: *support.Queue({resp})) ErrorSet!void"
            call = f"return self.server.{name}(reader_queue, writer_queue);"
        lines.append(f"        {sig} {{")
        lines.append(f"            {call}")
        lines.append("        }")
        lines.append("")
    lines.append("    };")
    lines.append("}")
    lines.append("")
    out_file.write_text("\n".join(lines))

# remove original nested layout
for path in sorted((out_root / "neo").rglob("*"), reverse=True):
    if path.is_file():
        path.unlink()
    elif path.is_dir():
        try:
            path.rmdir()
        except OSError:
            pass
try:
    (out_root / "neo").rmdir()
except OSError:
    pass

# zig-protobuf flattens nested messages incorrectly for object.Header/Split.
object_types = out_root / "object" / "types.pb.zig"
if object_types.exists():
    text = object_types.read_text().replace("Header.Split", "Split")
    text = text.replace("std.ArrayListUnmanaged(Header.Attribute)", "std.ArrayListUnmanaged(Attribute)")
    text = text.replace("split: ?Split = null", "split: ?*Split = null")
    split_marker = "/// Bigger objects can be split into a chain of smaller objects."
    header_methods = "\n    /// Encodes the message to the writer\n    /// The allocator is used to generate submessages internally.\n    /// Hence, an ArenaAllocator is a preferred choice if allocations are a bottleneck.\n    pub fn encode("
    object_marker = "/// Object structure. Object is immutable and content-addressed."
    # Only relocate when Split was emitted between Attribute and Header methods.
    attr_split = text.find("};\n\n" + split_marker)
    if attr_split != -1:
        start = attr_split + len("};\n\n")
        split_decl = text.find("pub const Split = struct", start)
        if split_decl != -1:
            depth = 0
            split_end = start
            for i, ch in enumerate(text[split_decl:], start=split_decl):
                if ch == "{":
                    depth += 1
                elif ch == "}":
                    depth -= 1
                    if depth == 0:
                        split_end = text.find("};", i) + 2
                        break
            split_block = text[start:split_end]
            text = text[:start] + text[split_end:]
            insert_at = text.find(object_marker)
            if insert_at != -1:
                text = text[:insert_at] + split_block + "\n" + text[insert_at:]
    object_types.write_text(text)

root_lines = ["// Code generated by scripts/genapi.sh."]
for module in sorted(set(modules)):
    root_lines.append(f'pub const {module} = @import("{module}/types.pb.zig");')
root_lines.append("")
(out_root / "root.zig").write_text("\n".join(root_lines))
PY

echo "generated protobuf bindings in ${OUT_DIR} (flattened package layout)"
